---
title: "STAT 757 Assignment 5"
subtitle: "DUE 4/01/2018 11:59PM"
author: "AG Schissler"
date: "2/14/2018"
output: pdf_document
fig_caption: true
exclude: true
caption: true
references:
- id: sheather2009
  title: A modern approach to regression with R
  author:
  - family: Sheather
    given: Simon
  publisher: Springer Science \& Business Media
  type: book
  issued:
    year: 2009
---

## Instructions [20 points]

Modify this file to provide responses to the Ch.5 Exercises in @sheather2009. You can find some helpful code here: [http://www.stat.
tamu.edu/~sheather/book/docs/rcode/Chapter5.R](http://www.stat.tamu.edu/~sheather/book/docs/rcode/Chapter5.R). Also address the project milestones indicated below. Please email **both** your .Rmd (or roxygen .R) and one of the following either .HTML, .PDF, or .DOCX using the format SURNAME-FIRSTNAME-Assignment5.Rmd and SURNAME-FIRSTNAME-Assignment5.pdf.

## Choose either Exercise 5.4.2 or 5.4.3. Respond to all parts posed. [60 points] 

## Project milestones [20 points]

1. Perform an exploratory data analysis:
 * Numerically summarize the variables.
 * Make plots and explore relationships between variables.
 * Identify any strange points or anything else that doesn't make sense.
2. Begin to think about how to model the relationships in your data.

## References
